name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - "v*"

env:
  DOCKER_SERVER_HOST: docker.io
  DOCKER_PROJECT_PATH: someblackmagic/alert-mapper
  DOCKER_NODE_VERSION: 14

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out code
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
#      - name: DockerTag
#        id: docker-tag
#        uses: yuya-takeyama/docker-tag-from-github-ref-action@v1

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v1
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build base image
        run: bash .pipelines/build_images.sh

      - name: Push image
        run: bash .pipelines/push_images.sh


